### ISSUE TITLE
Добавление сообщений после команды.

### ISSUE THREAD

**Issue by mstiya** [asvbkr/TamTamBot#1]
Не хватает сообщений после команды.
Например, после любой команды написать сообщение. (/command text). 
В нынешнем состоянии бот выбьет ошибку (/command text. Некорректная команда).
Так вот, хотелось бы, чтобы можно было так делать.
Пример команд:
/time Сколько времени? (Ответ: Сегодня 8:30)
/say Скажи Привет (Ответ: Привет)
/date Какая сейчас дата? (Ответ: Дата - 28.06.2019)

**Comment by asvbkr** [comment]
Добавлена возможность обработки команд с "аргументами" типа "/say Hello!".  
В этом случае будет вызван обработчик cmd_handler_say, а "Hello" будет находиться в переменной update.cmd_arg['l1']['c1']  - строка1, колонка 1
В случае "/say Hello, world!":
"Hello," -> update.cmd_arg['l1']['c1']
"world!" -> update.cmd_arg['l1']['c2']

**Comment by mstiya** [comment]
Большое вам спасибо!

пт, 28 июн. 2019 г. в 23:14, asvbkr <notifications@github.com>:

> Добавлена возможность обработки команд с "аргументами" типа "/say Hello!".
> В этом случае будет вызван обработчик cmd_handler_say, а "Hello" будет
> находиться в переменной update.cmd_arg['l1']['c1'] - строка1, колонка 1
> В случае "/say Hello, world!":
> "Hello," -> update.cmd_arg['l1']['c1']
> "world!" -> update.cmd_arg['l1']['c2']
