### ISSUE TITLE
наименования

### ISSUE THREAD

**Issue by Skorpyon** [asvbkr/TamTamBot#2]
```python 
from TamTamBot.TamTamBot import TamTamBot
```

Really?
Я не берусь хейтить там-там, хотя у меня отношение к нему такое же презрительное как у всех.
Но. CamelCase в питоне по договоренности используется только для классов.
Модуль в кемел-кейсе, имя файла (!) в кемел-кейсе...
Зачем вы так? Это же не JS и не PHP еще какой, это же па-а-айтон.

должно быть что-то вроде

```python
from tamtambot.bot import TamTamBot
```

upd.
А по хорошему, так бот это основной класс, поэтому его нужно импортировать в основное пространство имен модуля, и завершиться все должно чем-то а ля:

```python
from tamtambot import Bot
```

**Comment by asvbkr** [comment]
> ```python
> from TamTamBot.TamTamBot import TamTamBot
> ```
> 
> Really?
> Я не берусь хейтить там-там, хотя у меня отношение к нему такое же презрительное как у всех.
> Но. CamelCase в питоне по договоренности используется только для классов.
> Модуль в кемел-кейсе, имя файла (!) в кемел-кейсе...
> Зачем вы так? Это же не JS и не PHP еще какой, это же па-а-айтон.
> 
> должно быть что-то вроде
> 
> ```python
> from tamtambot.bot import TamTamBot
> ```
> 
> upd.
> А по хорошему, так бот это основной класс, поэтому его нужно импортировать в основное пространство имен модуля, и завершиться все должно чем-то а ля:
> 
> ```python
> from tamtambot import Bot
> ```

> ```python
> from TamTamBot.TamTamBot import TamTamBot
> ```
> 
> Really?
> Я не берусь хейтить там-там, хотя у меня отношение к нему такое же презрительное как у всех.
> Но. CamelCase в питоне по договоренности используется только для классов.
> Модуль в кемел-кейсе, имя файла (!) в кемел-кейсе...
> Зачем вы так? Это же не JS и не PHP еще какой, это же па-а-айтон.
> 
> должно быть что-то вроде
> 
> ```python
> from tamtambot.bot import TamTamBot
> ```
> 
> upd.
> А по хорошему, так бот это основной класс, поэтому его нужно импортировать в основное пространство имен модуля, и завершиться все должно чем-то а ля:
> 
> ```python
> from tamtambot import Bot
> ```
Спасибо за мнение. Изначально для себя делалось и не планировалось к распространению. В любом случае, теперь переделывать уже нецелесообразно.
